yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
app_name = 'group_list'

urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('author/', views.AboutAuthorView.as_view()),
    path('tech/', views.AboutTechView.as_view()),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path("create/", views.post_create, name="create"),
    path('posts/<int:post_id>/edit/',
         views.post_edit, name='post_edit'),
    path('', views.index, name='index'),
    path("404/", views.page_not_found, name="404"),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('', include('posts.urls', namespace='group_list')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/templates/includes/footer.html
<!DOCTYPE html> 
<html lang="ru"> 
  <body>
    <footer class="border-top text-center py-3">
      <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>     
    </footer>
  </body>

yatube/templates/includes/header.html
<!DOCTYPE html> 
{% load static %}
<html lang="ru"> 
  <body>
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'posts:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>
          <ul class="nav nav-pills">
            <li class="nav-item"> 
              <a class="nav-link 
                {% if request.resolver_match.view_name  == 'about:author' %}
                  active
                {% endif %}" 
                href="{% url 'about:author' %}"
                >Об авторе
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link
              {% if request.resolver_match.view_name  == 'about:tech' %}
                active
              {% endif %}" 
              href="{% url 'about:tech' %}">Технологии
              </a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item"> 
              <a class="nav-link
              {% if request.resolver_match.view_name  == 'posts:create' %}
                active
              {% endif %}"
              href="{% url 'posts:create' %}">Новая запись
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light
              {% if request.resolver_match.view_name  == 'about:tech' %}
                active
              {% endif %}"
              href="{% url 'about:tech' %}">Изменить пароль
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light
              {% if request.resolver_match.view_name  == 'users:logout' %}
                active
              {% endif %}"
              href="{% url 'users:logout' %}">Выйти
              </a>
            </li>
            <li>
              Пользователь: {{ user.username }}
            </li>
            {% else %}
            <li class="nav-item"> 
              <a class="nav-link link-light
              {% if request.resolver_match.view_name  == 'users:login' %}
                active
              {% endif %}"
              href="{% url 'users:login' %}">Войти
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light
              {% if request.resolver_match.view_name  == 'users:signup' %}
                active
              {% endif %}"
              href="{% url 'users:signup' %}">Регистрация
              </a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>      
    </header> 
  </body>

yatube/templates/includes/paginator.html
{# templates/posts/includes/paginator.html #}

{# Отрисовываем навигацию паджинатора только если все посты не помещаются на первую страницу #}

{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %} 