yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
app_name = 'group_list'

urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('author/', views.AboutAuthorView.as_view()),
    path('tech/', views.AboutTechView.as_view()),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path("create/", views.post_create, name="create"),
    path('posts/<int:post_id>/edit/',
         views.post_edit, name='post_edit'),
    path('', views.index, name='index'),
    path("404/", views.page_not_found, name="404"),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('', include('posts.urls', namespace='group_list')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='group_list',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )

    def __str__(self):
        return self.text[:15]

yatube/posts/forms.py
from django.forms import ModelForm
from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        labels = {'group': 'Группа', 'text': 'Сообщение'}
        help_texts = {'group': 'Выберите группу', 'text': 'Введите ссообщение'}
        fields = ["group", "text"]

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db import models
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.base import TemplateView
from .forms import PostForm
from .models import Group, Post


User = get_user_model()


class Posts(models.Model):
    number_of_posts = 10

    class Meta:
        abstract = True


def paginator(page_number, post_list):
    paginator = Paginator(post_list, Posts.number_of_posts)
    return paginator.get_page(page_number)


def index(request):
    post_list = Post.objects.select_related('author').all().order_by(
        '-pub_date')
    page_number = request.GET.get('page')
    page_obj = paginator(page_number, post_list)
    context = {
        'page_obj': page_obj,
        'title': 'Последние посты'
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter(group=group).order_by('-pub_date')
    page_number = request.GET.get('page')
    page_obj = paginator(page_number, post_list)
    context = {
        'title': f'Записи сообщества "{group.title}"',
        'page_obj': page_obj,
        'group': group,
    }
    return render(request, 'posts/group_list.html', context)


class AboutTechView(TemplateView):

    template_name = 'app_name/tech.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['just_title'] = 'Очень простая страница'
        context['text_1'] = ('Страница «Технологии»')
        context['just_text'] = ('На создание этой страницы '
                                'у меня ушло пять минут! Ай да я.')
        return context


class AboutAuthorView(TemplateView):

    template_name = 'app_name/author.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['just_title'] = 'Очень простая страница'
        context['text_1'] = ('Страница «Об авторе»')
        context['just_text'] = ('На создание этой страницы '
                                'у меня ушло пять минут! Ай да я.')
        return context


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all().order_by('-pub_date')
    page_number = request.GET.get('page')
    page_obj = paginator(page_number, posts)
    context = {'page_obj': page_obj,
               'posts': posts,
               'author': author, }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    count_posts = Post.objects.select_related('author').filter().count()
    context = {'post': post,
               'count_posts': count_posts,
               }
    return render(request, 'posts/post.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user.username)
    return render(request, 'new.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(request.POST, instance=post)
    edit = True
    if form.is_valid():
        post = form.save()
        post.author = request.user
        post.save()
        return redirect('posts:post_detail', post_id)
    else:
        form = PostForm(instance=post)
        context = {'edit': edit,
                   'form': form,
                   'post_id': post_id, }
    return render(request, 'new.html', context)


def page_not_found(request, exception, template_name='404.html'):
    response = render(request, template_name)
    response.status_code = 404
    return response

yatube/templates/posts/group_list.html
<!DOCTYPE html>
{% extends 'base.html' %} 
<html lang="ru">
  {% block head %}
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <title>{{ group }}</title>
  </head>
  {% endblock %} 
{% block content %}
  <body>
    <main>
      <div class="container py-5">
        <h1>{% block header %}{{ group.title }}{% endblock %}</h1>
        <p>{{ group.description  }}</p>
        <p> описание_группы </p>
        {% for post in page_obj %}
        <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p> {{ post.text }} </p>
        {% if post.group %}
        <a 
          href="{% url 'posts:group_list' post.group.slug %}">
          все записи группы
        </a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
        </article>
        {% endfor %}
      </div>  
    </main>
  </body>
{% include 'includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/index.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% extends 'base.html' %} 
<html lang="ru"> <!-- Язык сайта - русский -->
  {% block head %}
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <title>{{ title }}</title>
  </head>
  {% endblock %} 
{% block content %}
<body>
  <main> 
    <div class="container py-5">     
      {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
      </article>  
      {% if post.group %}    
      <a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы
      </a>
      {% endif %} 
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %} 
      <!-- под последним постом нет линии -->
    </div>  
  </main>
</body>
{% include 'includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/post.html
{% extends "base.html" %}
{% block title %}
  Пост {{title}}
{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
          {% if post.group %} 
            <li class="list-group-item">
                Группа: {{ post.group.title }}
                <a href="{% url 'posts:group_list' post.group.slug %}">
                  все записи группы
                </a>
          {% endif %}
              </li>
              <li class="list-group-item">
                Автор: {{ post.author.get_full_name }}
              </li>
              {% if user == post.author %}
              <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
                Редактировать запись
              </a>
            {% endif %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span > {{ posts_count }} </span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
      </ul>
    </aside>
      <article class="col-12 col-md-9">
        <p>{{ post.text }} </p>
      </article>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}
  Пост {{title}}
{% endblock %}
  <head>  
    <title>Профайл пользователя {{ author }}</title>
  </head>
{% block content %}
  <body>       
    <main>
      <h1>Все посты пользователя {{ author }} </h1>
      <h3>Всего постов: {{ author.posts.count }} </h3>
      {% for post in page_obj %}
      <div class="container py-5">        
         
        <article>
          <ul>
            <li>
              Автор: {{ author }}
              <a href= "{% url 'posts:profile' author.username %}" >все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>{{ post.text }}
          </p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
        </article>
        {% if post.group%}       
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>  
        {% endif %}      
        <hr>
        <!-- Остальные посты. после последнего нет черты -->
        
      </div>
      {% endfor %}
    </main>
    {% include 'includes/paginator.html' %}
  </body>
{% endblock %}  